### PR TITLE
fix(dev): add missing dev dependencies

### PR DESCRIPTION
**Pull request by cwillisf**
`npm test` doesn't work without installing these.

### CODE REVIEW

**Comment by rschamp** [comment]
Great, thanks!

**Comment by rschamp** [comment]
I should have mentioned this — since the commit is a `fix` it will cause a version bump. But since this was for development process only, I think it should have been a `chore`.  As far as I can tell, `fix` == patch bump, `feat` == minor bump, and then anything with BREAKING CHANGE == major bump.  Weirdly they don't document what causes which version bumps anywhere that I can find, but I will document my best guess in the README.

**Comment by cwillisf** [comment]
Oops, sorry about that... that wasn't my intent :/

**Comment by rschamp** [comment]
No worries, it doesn't actually matter and this is apparently the only documentation: https://github.com/semantic-release/commit-analyzer/blob/master/test/specs/index.js

**Comment by rschamp** [comment]
Documented! (in README)

**Pull request merged**
